### ISSUE TITLE
Add an useful python script!

### ISSUE THREAD

**Issue by arghac14** [fnplus/Python-scripts-collection#2]
1. Add any python script which should be able to solve a particular problem or to automate any monotonous task. 
2. Make sure the scripts does not already excist.
3. Make sure to add the description of the script and mention the dependencies/requirements in README.md

**Comment by arghac14** [comment]
@Arnie09 @SohelRaja wanna add some of those scripts here too? :)

**Comment by Arnie09** [comment]
Will I add my scripts in here?

**Comment by arghac14** [comment]
@Arnie09 yes go ahead
